### ISSUE TITLE
What is att_dist_model?

### ISSUE THREAD

**Issue by transformerwh** [horizonjohn/EffNet#1]
Hello, thank you for sharing. I would like to know what att_dist_model in src/att_dist.py is. I am looking forward to your answer. Thank you very much!

**Comment by horizonjohn** [comment]
> Hello, thank you for sharing. I would like to know what att_dist_model in src/att_dist.py is. I am looking forward to your answer. Thank you very much!

Thanks for your interest, it's the model backbone, in this study which we visualized is based on ViT/B-16, for more details you can see our arXiv paper.
